---

- name: create directory for module configuration
  become: true
  file:
    path: /etc/icingaweb2/modules/{{ item.key }}
    state: directory
    recurse: true
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.value.enabled is defined
    - item.value.enabled
    - item.value.configuration is defined
    - item.value.configuration | count > 0

- name: configure module
  become: true
  template:
    src: modules/{{ item.key }}/config.ini.j2
    dest: /etc/icingaweb2/modules/{{ item.key }}/config.ini
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0666
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.value.enabled is defined
    - item.value.enabled
    - item.value.configuration is defined
    - item.value.configuration | count > 0

- name: extract module information for grafana
  set_fact:
    _icingaweb_module_grafana: "{{ icingaweb_modules | dict_from_list('grafana') }}"

- name: create grafanas graphs.ini
  become: true
  template:
    src: modules/grafana/graphs.ini.j2
    dest: /etc/icingaweb2/modules/grafana/graphs.ini
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0666
  when:
    - _icingaweb_module_grafana is defined
    - _icingaweb_module_grafana.enabled | default('false')
    - _icingaweb_module_grafana.graphs | default({}) | count > 0

...
