---

- name: create directory for module configuration
  become: true
  file:
    path: /etc/icingaweb2/modules/{{ item.key }}
    state: directory
    recurse: true
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.enabled
    - item.configuration is defined
    - item.configuration | count > 0

- name: configure module
  become: true
  template:
    src: modules/{{ item.key }}/config.ini.j2
    dest: /etc/icingaweb2/modules/{{ item.key }}/config.ini
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0666
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  when:
    - item.enabled
    - item.configuration is defined
    - item.configuration | count > 0



...
