---

- name: download external modules to ansible controller
  become: false
  delegate_to: localhost
  ansible.builtin.git:
    depth: 1  # copy the least bit of history possible to get that repo.
    repo: "{{ item.value.src }}"
    version: "{{ item.value.version | default('') }}"
    dest: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}"
    update: true
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }} - version: {{ item.value.version | default('', true) }} - download: {{ item.value['download'] | default('true') | bool }}"
  when:
    - item.value['download'] | default('false') | bool

...
