---

- name: create module archive on ansible controller
  become: false
  delegate_to: localhost
  archive:
    path: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}"
    dest: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}.zip"
    mode: 0660
    remove: false
    format: zip
    exclude_path:
      - "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}/.git*"
    exclusion_patterns:
      - "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}/.git*"
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"
  when:
    - item.value['download'] | default('false') | bool
  # async: 1000
  # poll: 10

- name: define checksums from archive
  become: false
  delegate_to: localhost
  stat:
    path: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}.zip"
    checksum_algorithm: sha256
  register: _module_checksum
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"

- name: append checksums to icingaweb_modules
  set_fact:
    icingaweb_modules: "{{ icingaweb_modules | append_checksum(_module_checksum) }}"

- name: update facts
  setup:

- name: propagate modules archives
  become: true
  copy:
    src: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}.zip"
    dest: "{{ icingaweb_modules_remote_tmp_directory }}/"
    mode: 0660
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"
  when:
    - item.value['download'] | default('false') | bool

- name: create module directories
  become: true
  file:
    state: directory
    path: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"
  when:
    - item.value['download'] | default('false') | bool

- name: extract module archives
  unarchive:
    src: "{{ icingaweb_modules_remote_tmp_directory }}/{{ item.key }}.zip"
    #dest: "{{ icingaweb_modules_remote_tmp_directory }}/"
    #mode: 0700
    dest: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
    remote_src: true
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"
  register: _extract_archive
  when:
    - item.value['download'] | default('false') | bool

# - name: copy modules in place
#   become: true
#   copy:
#     src: "{{ icingaweb_modules_remote_tmp_directory }}/{{ item.key }}/"
#     dest: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}"
#     owner: "{{ icingaweb_user }}"
#     group: "{{ icingaweb_group }}"
#     remote_src: true
#     mode: 0750
#   loop:
#     "{{ icingaweb_modules | dict2items }}"
#   loop_control:
#     label: "module: {{ item.key }}"

- name: fix rights for modules
  become: true
  file:
    path: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
    recurse: true
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"
  when:
    - _extract_archive is defined
    - _extract_archive.changed

- name: create module checksum
  copy:
    dest: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}/.checksum"
    content: "{{ item.value.checksum }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0640
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }}"

- name: enable / disable modules
  become: true
  icingacli:
    state: "{{ 'enable' if item.enabled | default('true') else 'disable' }}"
    command: module
    module_name: "{{ item.key }}"
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "module: {{ item.key }} - enabled: {{ item.value.enabled | default('False', true) }}"

- name: create custom fact file
  template:
    src: facts.d/icingaweb2_modules.fact.j2
    dest: /etc/ansible/facts.d/icingaweb2_modules.fact
    owner: root
    group: root
    mode: 0755

...
