---

- name: create theme archive on ansible controller
  become: false
  delegate_to: localhost
  archive:
    path: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}"
    dest: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}.zip"
    mode: 0660
    remove: false
    format: zip
    exclude_path:
      - "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}/.git*"
    exclusion_patterns:
      - "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}/.git*"
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"
  async: 1000
  poll: 10

- name: define checksums from archive
  become: false
  delegate_to: localhost
  stat:
    path: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}.zip"
    checksum_algorithm: sha256
  register: _theme_checksum
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"

- name: append checksums to icingaweb_modules
  set_fact:
    icingaweb_modules: "{{ icingaweb_modules | append_checksum(_theme_checksum) }}"

- name: update facts
  setup:

- name: propagate modules archives
  become: true
  copy:
    src: "{{ icingaweb_modules_local_tmp_directory }}/{{ item.key }}.zip"
    dest: "{{ icingaweb_modules_remote_tmp_directory }}/"
    mode: 0660
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"

- name: extract theme archives
  unarchive:
    src: "{{ icingaweb_modules_remote_tmp_directory }}/{{ item.key }}.zip"
    dest: "{{ icingaweb_modules_remote_tmp_directory }}/"
    mode: 0700
    remote_src: true
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "theme: {{ item.key }}"

- name: copy modules in place
  become: true
  copy:
    src: "{{ icingaweb_modules_remote_tmp_directory }}/{{ item.key }}/"
    dest: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    remote_src: true
    mode: 0750
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "  theme: {{ item.key }}"

- name: create theme checksum
  copy:
    dest: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}/.checksum"
    content: "{{ item.value.checksum }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0640
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "  theme: {{ item.key }}"

- name: fix rights for modules
  become: true
  file:
    path: "{{ icingaweb_modules_install_dir }}/modules/{{ item.key }}"
    owner: "{{ icingaweb_user }}"
    group: "{{ icingaweb_group }}"
    mode: 0755
    recurse: true
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"

- name: enable / disable modules
  become: true
  icingacli:
    state: "{{ 'enable' if item.enabled | default('true') else 'disable' }}"
    command: module
    module_name: "{{ item.key }}"
  loop:
    "{{ icingaweb_modules | dict2items }}"
  loop_control:
    label: "  theme: {{ item.key }} - enabled: {{ item.value.enabled | default('False', true) }}"

- name: create custom fact file
  template:
    src: facts.d/icingaweb2_modules.fact.j2
    dest: /etc/ansible/facts.d/icingaweb2_modules.fact
    owner: root
    group: root
    mode: 0755

...
