---

icingaweb_themes:
  #
  unicorn:
    src: https://github.com/Mikesch-mp/icingaweb2-theme-unicorn.git
    version: v1.0.2
    images:
      - name: "unicorn.png"
        url: "http://i.imgur.com/SCfMd.png"
    enabled: true
  #
  batman-dark:
    src: https://github.com/jschanz/icingaweb2-theme-batman-dark.git
    version: v1.0.0
    enabled: false
    #images: []
  #
  dark:
    src: https://github.com/flyingchewbacca/icingaweb2-theme-dark.git
    version: master
    #images: []
  #
  lsd:
    src: https://github.com/Mikesch-mp/icingaweb2-theme-lsd.git
    version: v1.0.3
    #images: []
  #
  nordlicht:
    src: https://github.com/netzwerkgoettin/icingaweb2-theme-nordlicht.git
    version: master
    #images: []
  #
  spring:
    src: https://github.com/Mikesch-mp/icingaweb2-theme-spring.git
    version: v1.0.0
    #images: []
  #
  starwars-dark:
    src: https://github.com/marekbeckmann/IcingaWeb2-Star-Wars-Theme.git
    version: main
    images:
      - name: icon.png
        url: https://www.pngkit.com/png/full/75-757133_logo-star-wars-star-wars-logo-black-and.png
      - name: wallpaper.jpg
        url: https://wallpapercave.com/wp/wp7419777.jpg

...
