---

icingaweb_modules:
  audit:
    enabled: true
    src: https://github.com/Icinga/icingaweb2-module-audit.git
    version: v1.0.2
    configuration:
      log:
        type: file
        path: /var/log/icingaweb2/audit.log
      stream:
        format: json
        path: /var/log/icingaweb2/json.log

  pdfexport:
    enabled: true
    src: https://github.com/Icinga/icingaweb2-module-pdfexport
    version: v0.10.2

  graphite:
    enabled: true
    src: https://github.com/Icinga/icingaweb2-module-graphite.git
    version: v1.2.1
    configuration:
      host: localhost
      ui:
        default_time_range: 12
        default_time_range_unit: hours

  grafana:
    enabled: true
    src: https://github.com/Mikesch-mp/icingaweb2-module-grafana.git
    version: v1.4.2
    configuration:
      host: tsdb.icinga.local
      enableLink: true
      defaultdashboard:
        # name: icinga2-default
        uid: Z-TfDRpGz
      ##  publichost
      ##  publicprotocol
      ##  debug: true
    graphs:
      ping4:
        dashboard: hostalive
        dashboarduid: Z-TfDRpGz
        panelId: 9
        orgId: 1
        repeatable: false
      hostalive:
        dashboard: hostalive
        dashboarduid: Z-TfDRpGx
        panelId: 10
        orgId: 1
        repeatable: false

...
